# Generated by Django 5.2.1 on 2025-05-17 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PC', 'Computador'), ('LT', 'Portátil')], max_length=2)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('serial', models.CharField(max_length=100, unique=True)),
                ('procesador', models.CharField(max_length=100)),
                ('ram', models.CharField(max_length=50)),
                ('disco_duro', models.CharField(max_length=50)),
                ('sistema_operativo', models.CharField(max_length=100)),
                ('asignado_a', models.CharField(blank=True, max_length=100)),
                ('fecha_compra', models.DateField(blank=True, null=True)),
                ('fecha_instalacion', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios', to='inventario.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.dependencia')),
            ],
        ),
        migrations.AddField(
            model_name='equipo',
            name='salon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.salon'),
        ),
        migrations.AddField(
            model_name='dependencia',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.sede'),
        ),
    ]
