# Generated by Django 5.2.1 on 2025-05-17 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_equipo_dependencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='salon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.salon'),
        ),
    ]
