# Generated by Django 5.2.1 on 2025-05-17 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_historialcambio_usuario_alter_historialcambio_equipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialcambio',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios', to='inventario.equipo'),
        ),
    ]
